name: WG-github-actions_dispatch
run-name: workfrow to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      input1:
        type: boolean
      input2:
        description: 'input2 guild text'
        default: 'select2'
        type: choice
        options:
        - select1
        - select2
        - select3

jobs:
  job_id1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.input1}}"
          echo "${{ inputs.input2}}"
