name: WG-github-actions
run-name: workfrow to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
env:
  Workfrow_env: Workfrow

defaults:
  run:
    shell: bash
    working-directory: scripts

jobs:
  job-_id_1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo test1

  job-_id_2:
    name: job2
    runs-on: ubuntu-latest
    needs: job-_id_1
    if: always()
    defaults:
      run:
        shell: shell
    steps:
      - name: step1
        run: |
          echo test2
