name: WG-github-actions
run-name: workfrow to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
env:
  Workfrow_env: Workfrow

jobs:
  job-_id_1:
    runs-on: ubuntu-latest
    steps:
        run: |
          echo "### job1 :rocket:" >> $GITHUB_STEP_SUMMARY

  job-_id_2:
    runs-on: ubuntu-latest
    steps:
        run: |
          echo "### job2 ###" >> $GITHUB_STEP_SUMMARY
          echo "Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
