name: WG-github-actions
run-name: workfrow to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
env:
  TEST_ENV: 1
jobs:
  job_id_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo step1
      - name: step2
        run: echo step2


